liste_materiel = [
    "Herse de Prairie 6m",
    "Herse de Prairie 8m",
    "Herse étrille 6m",
    "Herse étrille 9m",
    "Herse rotative 3m",
    "Herse rotative 4m",
    "Herse rotative 6m",
    "Rouleau cambridge 6m",
    "Rouleau cambridge 8m",
    "Rouleau spire 4m",
    "Rouleau spire 6m",
    "Rouleau destructeur 3m - simple rouleau",
    "Rouleau destructeur 3m - doubles rouleaux",
    "Giro axe vertical 1m80",
    "Axe horizontal 3m",
    "Axe horizontal 4m80",
    "Axe vertical 4 à 5 m",
    "Axe vertical 6m",
    "Semoir mécanique 3m",
    "Semoir mécanique 4m",
    "Semoir mécanique 5m",
]